name: Build with Mason

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y meson ninja-build clang

    - name: Setup and build
      run: |
        meson setup build
        meson compile -C build
